# Generated by Django 5.1.2 on 2024-10-21 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game_requests", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="gamerequest",
            table="game_requests",
        ),
    ]
