# Generated by Django 5.1.2 on 2024-10-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_requests", "0002_alter_gamerequest_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamerequest",
            name="status",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="gamerequest",
            name="amount",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="gamerequest",
            name="price",
            field=models.PositiveIntegerField(),
        ),
    ]
