# Generated by Django 5.1.2 on 2024-10-21 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game_requests", "0003_gamerequest_status_alter_gamerequest_amount_and_more"),
        ("games", "0002_game_views_alter_game_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamerequest",
            name="game",
            field=models.ForeignKey(db_column="game_id", on_delete=django.db.models.deletion.CASCADE, to="games.game"),
        ),
        migrations.AlterField(
            model_name="gamerequest",
            name="mate",
            field=models.ForeignKey(
                db_column="mate_id", on_delete=django.db.models.deletion.CASCADE, related_name="mate", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="gamerequest",
            name="user",
            field=models.ForeignKey(db_column="user_id", on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
