# Generated by Django 5.1.2 on 2024-10-22 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("game_requests", "0004_alter_gamerequest_game_alter_gamerequest_mate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("rating", models.FloatField(max_length=5)),
                ("content", models.CharField(max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "game_request",
                    models.ForeignKey(
                        db_column="game_request_id", on_delete=django.db.models.deletion.CASCADE, to="game_requests.gamerequest"
                    ),
                ),
            ],
            options={
                "db_table": "review",
            },
        ),
    ]
