# Generated by Django 5.1.2 on 2024-10-18 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Game",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("리그 오브 레전드", "리그 오브 레전드"),
                            ("오버워치", "오버워치"),
                            ("전략적 팀 전투", "전략적 팀 전투"),
                            ("배틀그라운드", "배틀그라운드"),
                        ],
                        max_length=255,
                    ),
                ),
                ("image", models.CharField(max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
