# Generated by Django 5.1.2 on 2024-10-18 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("games", "add_game"),
    ]

    operations = []
