# Generated by Django 5.1.2 on 2024-10-20 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mates", "0002_alter_mategameinfo_game_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mategameinfo",
            name="level",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
