# Generated by Django 5.1.2 on 2024-10-21 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mates", "0003_alter_mategameinfo_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mategameinfo",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="mates/images/"),
        ),
    ]
