# Generated by Django 5.1.2 on 2024-10-18 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatRoom",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "main_user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="main_user", to=settings.AUTH_USER_MODEL),
                ),
                (
                    "other_user",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="other_user", to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "unique_together": {("main_user", "other_user")},
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sender_nickname", models.CharField(max_length=10)),
                ("text", models.TextField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("room", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="chats.chatroom")),
            ],
        ),
    ]
